# Generated by Django 4.1.3 on 2022-12-03 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
