# Generated by Django 4.1.3 on 2022-12-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_index_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
